//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranningMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using TranningMVCApp.Common;

    public partial class NewEmployee
    {
        [Range(1,100)]
        public int EmployeeID { get; set; }

        [Required]
        [Remote("isUserNameExists", "NewEmployees",ErrorMessage ="FirstName Already Exists!")]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }

        //In Range is fix what if we use current date as max so we create custom attribute
        //[Range(typeof(DateTime),"01/01/2020","01/01/2023")]
        [DateRange("01/01/2020")] //for maximum range
        [CurrentDate] //for minimum date
        [DisplayFormat(DataFormatString = "{0:d}",ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
